"""SCons build script for MAX30102 sensor driver."""

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]
group = DefineGroup('Drivers', src, depend = ['HR_USING_MAX30102'], CPPPATH = CPPPATH)

Return('group')
